module: src.client.agents.HTTPAgent
parameters:
  url: https://api.fireworks.ai/inference/v1/chat/completions
  headers:
    Content-Type: application/json
    Authorization: Bearer fr1xijf2EO0NvwGKLyhY3QbkLly9EUzcuyzt5u6vq3ne2vAA
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
