module: src.client.agents.HTTPAgent
parameters:
  name: <% NAME %>
  url: https://api.fireworks.ai/inference/v1/chat/completions
  headers:
    Content-Type: application/json
    Authorization: Bearer fr1xijf2EO0NvwGKLyhY3QbkLly9EUzcuyzt5u6vq3ne2vAA
  body:
    model: <% NAME %>
    temperature: 0
  prompter:
    name: prompt_string
  return_format: "{response[choices][0][text]}"

