import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    os-std: 5
  agent:
    firefunction-v2: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - firefunction-v2
    task:
      - dbbench-std
      - os-std

output: "outputs/{TIMESTAMP}"
